# Generated by Django 5.2 on 2025-06-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_galleryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
