# Generated by Django 5.2 on 2025-06-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutpageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('industrial_gases', 'Industrial Gases'), ('medical_gases', 'Medical Gases'), ('cryogenic_equipment', 'Cryogenic Equipment'), ('gas_cylinders', 'Gas Cylinders'), ('gas_installations', 'Gas Installations'), ('technical_services', 'Technical Services')], max_length=32, unique=True)),
                ('image', models.ImageField(upload_to='services/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
